name: Build & Package

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      dummy_tag:
        description: Version string
        default: 0.0.0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore -p:GeneratePackageOnBuild=false
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Pack (dummy)
      if: github.event_name == 'workflow_dispatch'
      run: dotnet pack --output ./nupkg --configuration Release -p:PackageVersion=${{github.event.inputs.dummy_tag}}
    - name: Pack
      run: dotnet pack --output ./nupkg --configuration Release -p:PackageVersion=${{GITHUB_REF/refs\/tags\//}}
      if: startsWith(github.ref, 'refs/tags/') && !(github.event_name == 'workflow_dispatch')
    - name: Upload .nupkg file (dummy)
      uses: actions/upload-artifact@v2
      if: github.event_name == 'workflow_dispatch'
      with:
        path: ./nupkg/IgorTextFormatter.${{github.event.inputs.dummy_tag}}.nupkg
    - name: Upload .nupkg file
      uses: actions/upload-artifact@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        path: ./nupkg/IgorTextFormatter.${{GITHUB_REF/refs\/tags\//}}.nupkg

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/') && !(github.event_name == "workflow_dispatch")
      run: dotnet nuget push ./nupkg/IgorTextFormatter/IgorTextFormatter/bin/Release/.${{github.event.inputs.dummy_tag}}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
