name: Build & Package

on:
  push:
    branches: '*'
  release: 
    types: published
  workflow_dispatch:
    inputs:
      dummy_tag:
        description: Version string
        default: 0.0.0

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5', '6']

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET ${{matrix.dotnet-version}}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{matrix.dotnet-version}}
    - name: Restore dependencies
      run: dotnet restore IgorTextFormatter.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore -p:GeneratePackageOnBuild=false IgorTextFormatter.sln
    - name: Test
      run: dotnet test --framework 'net${{matrix.dotnet-version}}.0' --configuration Release --no-build --verbosity normal

  pack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6
    - run: dotnet build --configuration Release
    - name: Pack (dummy)
      if: ${{!(startsWith(github.ref, 'refs/tags/') && !(github.event_name == 'workflow_dispatch'))}}
      run: dotnet pack --output ./nupkg --configuration Release -p:PackageVersion=0.0.0
    - name: Pack
      if: ${{startsWith(github.ref, 'refs/tags/') && !(github.event_name == 'workflow_dispatch')}}
      run: dotnet pack --output ./nupkg --configuration Release -p:PackageVersion=${GITHUB_REF#refs/tags/}
    - name: Upload .nupkg file (dummy)
      uses: actions/upload-artifact@v4
      if: ${{!(startsWith(github.ref, 'refs/tags/') && !(github.event_name == 'workflow_dispatch'))}}
      with:
        path: ${{ github.workspace }}/nupkg/IgorTextFormatter.0.0.0.nupkg
    - name: Upload .nupkg file
      uses: actions/upload-artifact@v4
      if: ${{startsWith(github.ref, 'refs/tags/') && !(github.event_name == 'workflow_dispatch')}}
      with:
        path: ${{ github.workspace }}/nupkg/IgorTextFormatter.${GITHUB_REF#refs/tags/}.nupkg
        
  publish:
    needs: [build, pack]
    runs-on: ubuntu-latest
    if: ${{startsWith(github.ref, 'refs/tags/') && !(github.event_name == 'workflow_dispatch')}}
    steps:
    - name: Download .nupkg file
      uses: actions/download-artifact@v4
    - name: Publish
      run: dotnet nuget push IgorTextFormatter.${{ github.workspace }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
