name: Build & Package

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      dummy_tag:
        description: Version string
        default: 0.0.0

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5', '6']

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET ${{matrix.dotnet-version}}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{matrix.dotnet-version}}
    - name: Restore dependencies
      run: dotnet restore IgorTextFormatter.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore -p:GeneratePackageOnBuild=false IgorTextFormatter.sln
    - name: Test
      run: dotnet test --framework 'net${{matrix.dotnet-version}}.0' --configuration Release --no-build --verbosity normal
      
    - name: Pack (dummy)
      if: github.event_name == 'workflow_dispatch'
      run: dotnet pack --output ./nupkg --configuration Release -p:PackageVersion=${{github.event.inputs.dummy_tag}}
    - name: Pack
      run: dotnet pack --output ./nupkg --configuration Release -p:PackageVersion=${GITHUB_REF#refs/tags/}
      if: startsWith(github.ref, 'refs/tags/') && !(github.event_name == 'workflow_dispatch')
    - name: Upload .nupkg file (dummy)
      uses: actions/upload-artifact@v4
      if: github.event_name == 'workflow_dispatch'
      with:
        path: ./nupkg/IgorTextFormatter.${{github.event.inputs.dummy_tag}}.nupkg
    - name: Upload .nupkg file
      uses: actions/upload-artifact@v4
      if: startsWith(github.ref, 'refs/tags/')
      with:
        path: ./nupkg/IgorTextFormatter.${GITHUB_REF#refs/tags/}.nupkg

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/') && !(github.event_name == 'workflow_dispatch')
      run: dotnet nuget push ./nupkg/IgorTextFormatter.${GITHUB_REF#refs/tags/}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
